version: '3.7'

services:
  app:
    build:
      context: .
    image: socialimagerecog
    ports:
      - "8080:8080"
    # command: sh -c "uvicorn app:app --host 0.0.0.0 --port ${PORT}"
    command: bash -c "source venv/bin/activate && uvicorn app:app --host 0.0.0.0 --port 8080"

  datadog:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
